language: node_js
sudo: required
# 指定node_js版本
node_js: 
  - 7.9.0
# 指定缓存模块，可选。缓存可加快编译速度。


cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save


# before_script:
#  - npm install -g gulp

script:
  - hexo clean
  - hexo g 

after_script:
  - git config user.name "chengzhaojia"
  - git config user.email "380333756@qq.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/czjroy/hexo.github.io.git